apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: bjkc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bjkc
    app.kubernetes.io/part-of: byoc-app-ojnb
  name: bjkc
spec:
  rules:
  - host: bjkc-byoc-afkh-tenant.apps.de3829ad6edc72278243.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: bjkc
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
