apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: bjkc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bjkc
    app.kubernetes.io/part-of: byoc-app-ojnb
  name: bjkc
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: bjkc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: bjkc
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-afkh-tenant/byoc-app-ojnb/bjkc@sha256:bd5290f0d70b4f2c1818e876b9b8d5a2c77af67c29121369417e82f3aae27451
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
